email: bharat.159753@gmail.com
description: Feel free to bookmark this site, to know about me and keep an eye on my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bha159.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bha159753
github_username:  bha159

# Build settings
markdown: kramdown
# theme: minima
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /projects/:path/